### PR TITLE
added option to force transactions

### PR DESCRIPTION
**Pull request by CarstenKoenig**
ok, I added the force option and removed the unwanted validation on the UI

BTW: seems it was not my fault after all, because I cannot create a pull-request to a yet non-existing branch on your side, not on github - [see here](https://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch)

### CODE REVIEW

**Comment by ralfw** [comment]
I merged, I see the force checkbox in the design view - but it does not show up when I run the project :-(

Also deposits are still not possible w/o a description.

Still strange that creating a new branch and issuing a pull request for that is not possible.

**Comment by CarstenKoenig** [comment]
there seems to be a really strange problem with the XAML parts - I think I saw this some time ago - you have to clean up the binaries (I would suggest remove ./obj and ./bin from disk) and rebuild everything

**Comment by CarstenKoenig** [comment]
update: I found it - the checkboxes to build the WPF project in the configuration manager is missing ... grrr (sorry)

**Comment by ralfw** [comment]
it's working. thx!

**Pull request merged**
