### PR TITLE
WPF UI

### PR DESCRIPTION
**Pull request by CarstenKoenig**
Hi, 

I added a basic WPF UI

right now it lacks the export functionality and only resembles the "rough look" of your napkin design.

It also does not implement an "head" as I for now think that it's easier to just hook up the body to the viewmodel, but it should be a no-brainer to change.

Also I init everything in the main-windows code-behind, most likely you'll want to add some application class and do it there.

aside from this I hope it's sufficient for you (or get's you started)

### CODE REVIEW

**Comment by ralfw** [comment]
Cool! Thanks a ton! This looks good enough for the moment.

Only two small issues regarding the implementation:
-Transactions in previous months are not possible; a force-switch is missing.
-The UI rejects deposits without a description. The domain logic, though, allows them.

And one basic issue: The UI is replicating domain logic. It enables/disables functionality not only because data is missing (no deposit w/o an amount) which means basic consistency is violated. But also the UI checks for logical conditions like a transaction date lying in the future. If the UI needs support in the, let the body know. It can help :-) It can provide additional functionality for the new GUI.

As for the term "head": I don't care how the WPF UI internally looks. It's a black box to me. The whole cashbook.wpf assembly is the head. Like the cashbook.console assembly is th CLI head. If you don't see a need for further structuring the internals of the cashbook.wpf project, well, that's your decision. The head does not need a class called Head{} if it's otherwise clearly separated from the body. Which it is in your case.

One question: How about submitting new code in a branch? Wouldn't that be more decoupling. I cannot assess the quality of the changes in a pull request by looking at the diffs. I need to pull the code. So I need to merge it. But then the master might already be "polluted". If the changes where in a branch, I could pull/merge, try it out locally - and then merge the changes into master.

Or am I missing something in the pull request workflow?

**Comment by CarstenKoenig** [comment]
- to the duplicated logic thing: yes that's true and easily removed (basically clear out `ValidateEdit` to `return true` in `MainViewModel.cs`
-  why are transactions into prvious months not possible? If I just set the date in the edit part to some date in the past it will ad it to accordingly (at least in my local branch)
- what's not working on my branch is the "Final balance" thing but I didn't care as this is not within the UIs responsibilities ;)

To the branch issue: indeed I had a local WPF branch - but the damn pull-request won't let me give another branch than your master while creating the pull-request. I honestly have no clue why this was the case (and I clicked the "create pull-request" without double-checking) - Sorry!

PS: Are you interested in how this thing could look in F#? I have a toy eventsourcing lib I could test with this problem - maybe I'll try it on my fork

**Comment by ralfw** [comment]
- i have to check the validation thing. not sure i understand how to bind to the body for help on validation before submitting a transaction.
- the requirements state that tx before the current month are possible - but need to be "forced". the CLI head provides a -f switch for that. a GUI could provide a checkbox (to be cleared after each tx).
- a final balance? was that a requirement? i only see balances at start/end of month - and they are part of the balance sheet.

strange that a pull request won't work for a branch. [here](https://help.github.com/articles/using-pull-requests/) it's explicitly recommended to use topic branches.

**Comment by CarstenKoenig** [comment]
for the pull request - yeah sorry - I'm sure I messed that up - I added "WPF" on _your side_ but it somehow switched back and I did not notice until it was to late

for the force: to be honest I used your code as a black box and did not look into it (and I only had a quick look on the readme) - so I force _everything_ (it's in the `Withdraw` and `Deposit` methods on the viewmodel in case you want to change it - of course I can add a checkbox too if you want ;)

as for the final balance: if this is no requirement then ok - just saying that it will not calculate correctly if I add another deposit in the past after i did some deposits / withdrawls in the current month.

**Comment by ralfw** [comment]
force: you see, reading the f\* requirements helps ;-) i'd much appreciate if you could add a force checkbox (do be cleared after each withdraw/deposit); default: false.

final balance: the final balance is per month. it's provided by the body. nothing to do for a head. thx for pointing out a bug in that.

**Pull request merged**
